apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: model
  name: model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model
  strategy: {}
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - image: lfarizav/house-price-model
        name: house-price-model
        ports:
        - containerPort: 8000
        resources: {}
status: {}
