apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubestronaut_fastapi
  name: kubestronaut_fastapi
spec:
  ports:
  - name: "8000"
    nodePort: 30100
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: kubestronaut_fastapi
  type: NodePort
status:
  loadBalancer: {}
