apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubestronaut_fastapi
  name: kubestronaut_fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubestronaut_fastapi
  strategy: {}
  template:
    metadata:
      labels:
        app: kubestronaut_fastapi
    spec:
      containers:
      - image: lfarizav/kubestronaut_fastapi
        name: kubestronaut_fastapi
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
status: {}
