model:
  best_model: XGBoost
  feature_sets:
    rfe:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '6'
    - '7'
    - '10'
    - '11'
    - '13'
  mae: 0.017808487773671538
  name: kubestronaut_model
  parameters:
    base_score: null
    booster: null
    callbacks: null
    colsample_bylevel: null
    colsample_bynode: null
    colsample_bytree: null
    early_stopping_rounds: null
    enable_categorical: false
    eval_metric: null
    feature_types: null
    gamma: null
    gpu_id: null
    grow_policy: null
    importance_type: null
    interaction_constraints: null
    learning_rate: 0.05
    max_bin: null
    max_cat_threshold: null
    max_cat_to_onehot: null
    max_delta_step: null
    max_depth: 3
    max_leaves: null
    min_child_weight: null
    missing: .nan
    monotone_constraints: null
    n_estimators: 150
    n_jobs: null
    num_parallel_tree: null
    objective: reg:squarederror
    predictor: null
    random_state: null
    reg_alpha: null
    reg_lambda: null
    sampling_method: null
    scale_pos_weight: null
    subsample: null
    tree_method: null
    validate_parameters: null
    verbosity: null
  r2_score: 0.9739723308208964
  target_variable: final_result
